apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.widgets.krateo.io
spec:
  insecureSkipTLSVerify: true
  group: widgets.krateo.io
  groupPriorityMinimum: 1000
  version: v1alpha1
  versionPriority: 15
  service:
    name: {{ include "backend.fullname" . }}
