apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "backend.fullname" . }}:system:auth-delegator
  labels:
    {{- include "backend.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name:  system:auth-delegator
subjects:
- kind: ServiceAccount
  name: {{ include "backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name:  {{ include "backend.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
