apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
rules:
# For API server
- apiGroups:
  - ""
  resources:
  - namespaces
  - configmaps
  - secrets
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - flowcontrol.apiserver.k8s.io
  resources:
  - prioritylevelconfigurations
  - flowschemas
  verbs:
  - list
  - watch
# For krateo stuffs
- apiGroups:
  - core.krateo.io
  resources:
  - compositiondefinitions
  - schemadefinitions
  verbs:
  - get
  - list
- apiGroups:
  - templates.krateo.io
  resources:
  - "*"
  verbs:
  - get
  - list
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
# For checking user permissions on resources
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - users
  - groups
  verbs:
  - impersonate
- apiGroups:
  - authentication.k8s.io
  resources:
  - userextras/authentication.k8s.io/pod-uid
  - userextras/authentication.k8s.io/pod-name
  - userextras/authentication.kubernetes.io/pod-uid
  - userextras/authentication.kubernetes.io/pod-name
  - userextras/authentication.kubernetes.io/node-uid
  - userextras/authentication.kubernetes.io/node-name
  - userextras/authentication.kubernetes.io/credential-id
  verbs:
  - impersonate
