apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "backend.fullname" . }}-extension-apiserver-authentication-reader
  namespace: kube-system
  labels:
    {{- include "backend.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name:  extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: {{ include "backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
