apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 443
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: https
  selector:
    {{- include "backend.selectorLabels" . | nindent 4 }}
