---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: widgets-viewer
  namespace: demo-system
rules:
- apiGroups:
  - templates.krateo.io
  resources:
  - '*'
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: widgets-viewer
  namespace: demo-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name:  widgets-viewer
subjects:
- kind: Group
  name: devs
  apiGroup: rbac.authorization.k8s.io