---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pods-viewer
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - pods/status
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pods-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name:  pods-viewer
subjects:
- kind: Group
  name: devs
  apiGroup: rbac.authorization.k8s.io
